

stages:
  - setup
  - base-build

Setup:
  stage: setup
  image: node:12-alpine
  script:
    - yarn install

Build base images:
  stage: base-build
  image: docker
  services:
    - docker:dind
  variables:
    ALPINE_VERSION: "3.11"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - cd base
  script:
    - docker build --build-arg ALPINE_VERSION=$ALPINE_VERSION -t wener/base base
  after_script:
    - docker push wener/base

    - docker tag wener/base wener/base:$ALPINE_VERSION
    - docker push wener/base:$ALPINE_VERSION

    - docker tag wener/base:$ALPINE_VERSION $CI_REGISTRY_IMAGE/wener/base
    - docker push wener/base:$ALPINE_VERSION $CI_REGISTRY_IMAGE/wener/base

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - .yarn/
