name: Build
on:
- push

jobs:
  Build:
    name: Build
    runs-on: alpine-exec
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
    # https://stackoverflow.com/a/74268200/1870054
    - name: Changes
      id: changes
      run: |
        if ${{ github.event_name == 'pull_request' }}; then
            echo "files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
        else
            echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
        fi

    - name: Docker Login
      run: |
        [ -z "$DOCKER_REGISTRY" ] || docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" "$DOCKER_REGISTRY"
        [ -z "${{ secrets.DOCKER_REGISTRY }}" ] || docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}" "${{ secrets.DOCKER_REGISTRY }}"

    - name: Build
      run: |
        set -eo pipefail
        export BUILDKIT_PROGRESS=plain

        make ci
