REPO_ROOT ?= $(shell git rev-parse --show-toplevel)
-include $(REPO_ROOT)/build.mk

# git describe from wenerme/mihomo develop branch
export VERSION:=1.19.21
# change MIHOMO_REV to bust docker cache when code updates
export MIHOMO_REV:=ccfa76f3

print:
push:
